<?php
class RecipeControllerTest extends Zend_Test_PHPUnit_ControllerTestCase
{
    
	private $fridge_ingredients = array ( 'bread' => array ( 'item' => 'Bread', 'amount' => 10, 'unit' => 'slices', 'use-by' => '2014-12-25', ), 'cheese' => array ( 'item' => 'cheese', 'amount' => 10, 'unit' => 'slices', 'use-by' => '2014-12-25', ), 'butter' => array ( 'item' => 'butter', 'amount' => 200, 'unit' => 'grams', 'use-by' => '2014-06-30', ), 'peanut butter' => array ( 'item' => 'peanut butter', 'amount' => 250, 'unit' => 'grams', 'use-by' => '2014-12-02', ), 'mixed salad' => array ( 'item' => 'mixed salad', 'amount' => 150, 'unit' => 'grams', 'use-by' => '2013-12-26', ), 'pasta' => array ( 'item' => 'pasta', 'amount' => 500, 'unit' => 'grams', 'use-by' => '2016-12-26', ), 'extra virgin olive oil' => array ( 'item' => 'extra virgin olive oil', 'amount' => 30, 'unit' => 'ml', 'use-by' => '2017-12-26', ), 'chilli flakes' => array ( 'item' => 'chilli flakes', 'amount' => 30, 'unit' => 'grams', 'use-by' => '2018-12-26', ), 'garlic' => array ( 'item' => 'garlic', 'amount' => 30, 'unit' => 'grams', 'use-by' => '2014-04-26', ), 'rice' => array ( 'item' => 'rice', 'amount' => 130, 'unit' => 'grams', 'use-by' => '2014-09-26', ), 'mushrooms' => array ( 'item' => 'mushrooms', 'amount' => 100, 'unit' => 'grams', 'use-by' => '2014-04-21', ), 'steak' => array ( 'item' => 'steak', 'amount' => 600, 'unit' => 'grams', 'use-by' => '2014-03-01', ), 'tomatoes' => array ( 'item' => 'tomatoes', 'amount' => 250, 'unit' => 'grams', 'use-by' => '2014-03-31', ), );
	private $recipes = array ( 0 => array ( 'name' => 'grilled cheese on toast', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'cheese', 'amount' => '2', 'unit' => 'slices', ), ), ), 1 => array ( 'name' => 'salad sandwich', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'mixed salad', 'amount' => '100', 'unit' => 'grams', ), ), ), 2 => array ( 'name' => 'pasta spicy', 'ingredients' => array ( 0 => array ( 'item' => 'pasta', 'amount' => '120', 'unit' => 'grams', ), 1 => array ( 'item' => 'garlic', 'amount' => '10', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '50', 'unit' => 'ml', ), 3 => array ( 'item' => 'chilli flakes', 'amount' => '3', 'unit' => 'grams', ), ), ), 3 => array ( 'name' => 'bruschetta', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'garlic', 'amount' => '10', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '25', 'unit' => 'ml', ), ), ), 4 => array ( 'name' => 'pasta with salmon', 'ingredients' => array ( 0 => array ( 'item' => 'pasta', 'amount' => '120', 'unit' => 'grams', ), 1 => array ( 'item' => 'salmon', 'amount' => '100', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '30', 'unit' => 'ml', ), ), ), 5 => array ( 'name' => 'steak', 'ingredients' => array ( 0 => array ( 'item' => 'steak', 'amount' => '500', 'unit' => 'grams', ), 1 => array ( 'item' => 'extra virgin olive oil', 'amount' => '20', 'unit' => 'ml', ), ), ), 6 => array ( 'name' => 'salad', 'ingredients' => array ( 0 => array ( 'item' => 'mixed salad', 'amount' => '100', 'unit' => 'grams', ), 1 => array ( 'item' => 'tomatoes', 'amount' => '100', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '20', 'unit' => 'ml', ), ), ), 7 => array ( 'name' => 'hamburger', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'mixed salad', 'amount' => '30', 'unit' => 'grams', ), 2 => array ( 'item' => 'tomatoes', 'amount' => '30', 'unit' => 'grams', ), 3 => array ( 'item' => 'steak', 'amount' => '200', 'unit' => 'ml', ), ), ), 8 => array ( 'name' => 'pasta with mushrooms', 'ingredients' => array ( 0 => array ( 'item' => 'pasta', 'amount' => '120', 'unit' => 'grams', ), 1 => array ( 'item' => 'mushrooms', 'amount' => '50', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '30', 'unit' => 'ml', ), ), ), );
	
    public function setUp()
    {
    	$application = new Zend_Application(
    			APPLICATION_ENV,
    			APPLICATION_PATH . '/configs/application.ini'
    	);
    
    	$this->bootstrap = $application;
    	return parent::setUp();
    }
    
    
    
    // Test of html
    public function testModel()
    {
    	$possible_recipes = Application_Model_Recipes::verify_recipes($this->recipes, $this->fridge_ingredients);
    	$possible_recipes_result_test = array ( 0 => array ( 'name' => 'pasta with mushrooms', 'ingredients' => array ( 0 => array ( 'item' => 'pasta', 'amount' => '120', 'unit' => 'grams', ), 1 => array ( 'item' => 'mushrooms', 'amount' => '50', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '30', 'unit' => 'ml', ), ), 'use-by' => '2014-04-21', ), 1 => array ( 'name' => 'bruschetta', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'garlic', 'amount' => '10', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '25', 'unit' => 'ml', ), ), 'use-by' => '2014-04-26', ), 2 => array ( 'name' => 'grilled cheese on toast', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'cheese', 'amount' => '2', 'unit' => 'slices', ), ), 'use-by' => '2014-12-25', ), );
    	$this->assertSame($possible_recipes_result_test, $possible_recipes);
    	
    	$not_possible_recipes_result_test = array ( 0 => array ( 'name' => 'salad sandwich', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'mixed salad', 'amount' => '100', 'unit' => 'grams', 'error' => array ( 0 => 'Ingredient expired', ), ), ), ), 1 => array ( 'name' => 'pasta spicy', 'ingredients' => array ( 0 => array ( 'item' => 'pasta', 'amount' => '120', 'unit' => 'grams', ), 1 => array ( 'item' => 'garlic', 'amount' => '10', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '50', 'unit' => 'ml', 'error' => array ( 0 => 'Insufficient quantity', ), ), 3 => array ( 'item' => 'chilli flakes', 'amount' => '3', 'unit' => 'grams', ), ), ), 2 => array ( 'name' => 'pasta with salmon', 'ingredients' => array ( 0 => array ( 'item' => 'pasta', 'amount' => '120', 'unit' => 'grams', ), 1 => array ( 'item' => 'salmon', 'amount' => '100', 'unit' => 'grams', 'error' => array ( 0 => 'Ingredient not found in the fridge', ), ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '30', 'unit' => 'ml', ), ), ), 3 => array ( 'name' => 'steak', 'ingredients' => array ( 0 => array ( 'item' => 'steak', 'amount' => '500', 'unit' => 'grams', 'error' => array ( 0 => 'Ingredient expired', ), ), 1 => array ( 'item' => 'extra virgin olive oil', 'amount' => '20', 'unit' => 'ml', ), ), ), 4 => array ( 'name' => 'salad', 'ingredients' => array ( 0 => array ( 'item' => 'mixed salad', 'amount' => '100', 'unit' => 'grams', 'error' => array ( 0 => 'Ingredient expired', ), ), 1 => array ( 'item' => 'tomatoes', 'amount' => '100', 'unit' => 'grams', ), 2 => array ( 'item' => 'extra virgin olive oil', 'amount' => '20', 'unit' => 'ml', ), ), ), 5 => array ( 'name' => 'hamburger', 'ingredients' => array ( 0 => array ( 'item' => 'bread', 'amount' => '2', 'unit' => 'slices', ), 1 => array ( 'item' => 'mixed salad', 'amount' => '30', 'unit' => 'grams', 'error' => array ( 0 => 'Ingredient expired', ), ), 2 => array ( 'item' => 'tomatoes', 'amount' => '30', 'unit' => 'grams', ), 3 => array ( 'item' => 'steak', 'amount' => '200', 'unit' => 'ml', ), ), ), );
    	$this->assertSame($possible_recipes_result_test, $possible_recipes);
    }
    
}
?>